# Custom Language File for Launcher Customizer

[ejs.app]
title = "Kaine Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Kaineoff/KaineLauncher"
mediaTwitterURL = "https://x.com/Kaine_Off"
mediaInstagramURL = "https://www.instagram.com/alexandre_bkrs/"
mediaYouTubeURL = "https://www.youtube.com/@Kaine_Off"
mediaTwitchURL = "https://www.twitch.tv/kaine_off"
mediaDiscordURL = "https://discord.gg/CrguZwKhHq"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur le Launcher Kaine Launcher"
welcomeDescription = "Ceci est un launcher entre amies pour les serveurs de KaineOff, merci de ne pas le partager à n'importe qui."
welcomeDescCTA = "You are just a few clicks away from KaineWorld."
